#!/bin/bash

if [ "$1" == "install" ]; then
  echo "Installing pre-commit hook"
  ln -s ../../pre-commit .git/hooks/pre-commit
  exit 0
fi

git stash -q --keep-index

echo "Running git pre-commit hook"

./gradlew ktlintCheck

RESULT=$?

git stash pop -q

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0
